config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  namespace :api, path: '/api' do
    mount RootAPI, at: '/'
    mount GrapeSwaggerRails::Engine => '/docs'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication_token.rb
class AuthenticationToken < ApplicationRecord
  belongs_to :user

  before_create :set_expires_at
  before_create :set_token

  scope :valid, -> { where('expires_at > ?', Time.zone.now) }

  def expire!
    update_columns(expires_at: Time.zone.now)
  end

  private

  def set_expires_at
    self.expires_at = Time.zone.now + 1.day
  end

  def set_token
    self.token = generate_token
  end

  def generate_token
    loop do
      token = SecureRandom.hex
      break token unless self.class.where(token: token).exists?
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_secure_password

  has_many :authentication_tokens, dependent: :destroy

  before_create :set_username

  validates :email, presence: true, uniqueness: true,
                    format: { with: EMAIL_REGEX,
                              message: 'format is invalid' }
  validates_length_of :password, confirmation: true, minimum: 8, allow_blank: true
  validates :username, presence: true, on: :update
  validates_length_of :username, minimum: 5, on: :update, if: :username_changed?

  private

  def set_username
    self.username = email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/serializers_helper.rb
module SerializersHelper
  def serialize(object, serializer:, **keys)
    serializer.new(object, **keys).as_json
  end

  def serialize_collection(collection, serializer:, **keys)
    ActiveModel::Serializer::CollectionSerializer.new(
      collection,
      serializer: serializer,
      **keys
    ).as_json
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.haml
%h1 Welcome to sample Simple Panel rails backend

%p Documentation: #{link_to 'link', api_grape_swagger_rails_path}
%p Github: #{link_to 'link', 'https://github.com/robertziel/simple_panel_rails_backend'}

%h4 Sample user login credentials:
%p email: hello@robertz.co
%p password: 12345678

%h2 React client
%p Live preview: #{link_to 'link', 'https://simple-panel-react-client.robertz.co/'}
%p Github: #{link_to 'link', 'https://github.com/robertziel/simple_panel_react_client'}

%h3 Designed by #{link_to 'Robert Zieliński', 'https://robertz.co'}